//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// InlineObject3 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "inline_object_3")]
    internal class InlineObject3
    {
        /// <summary>
        /// Creates an instance of InlineObject3.
        /// </summary>
        /// <param name="name">Name of the organization</param>
        /// <param name="industryType">Industry type of the organization</param>
        [Preserve]
        public InlineObject3(string name, IndustryTypeOptions industryType = default)
        {
            Name = name;
            IndustryType = industryType;
        }

        /// <summary>
        /// Name of the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name{ get; }
        /// <summary>
        /// Industry type of the organization
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        [DataMember(Name = "industryType", EmitDefaultValue = false)]
        public IndustryTypeOptions IndustryType{ get; }
    

        /// <summary>
        /// Industry type of the organization
        /// </summary>
        /// <value>Industry type of the organization</value>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        public enum IndustryTypeOptions
        {
            /// <summary>
            /// Enum Games for value: Games
            /// </summary>
            [EnumMember(Value = "Games")]
            Games = 1,

            /// <summary>
            /// Enum Gambling for value: Gambling
            /// </summary>
            [EnumMember(Value = "Gambling")]
            Gambling = 2,

            /// <summary>
            /// Enum MediaEntertainment for value: Media & Entertainment
            /// </summary>
            [EnumMember(Value = "Media & Entertainment")]
            MediaEntertainment = 3,

            /// <summary>
            /// Enum ArchitectureEngineeringConstruction for value: Architecture/Engineering/Construction
            /// </summary>
            [EnumMember(Value = "Architecture/Engineering/Construction")]
            ArchitectureEngineeringConstruction = 4,

            /// <summary>
            /// Enum AutoTransportationManufacturing for value: Auto/Transportation/Manufacturing
            /// </summary>
            [EnumMember(Value = "Auto/Transportation/Manufacturing")]
            AutoTransportationManufacturing = 5,

            /// <summary>
            /// Enum Education for value: Education
            /// </summary>
            [EnumMember(Value = "Education")]
            Education = 6,

            /// <summary>
            /// Enum PlatformPartner for value: Platform Partner
            /// </summary>
            [EnumMember(Value = "Platform Partner")]
            PlatformPartner = 7,

            /// <summary>
            /// Enum Other for value: Other
            /// </summary>
            [EnumMember(Value = "Other")]
            Other = 8

        }

    }
}

