//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// InlineObject2 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "inline_object_2")]
    internal class InlineObject2
    {
        /// <summary>
        /// Creates an instance of InlineObject2.
        /// </summary>
        /// <param name="destinationOrganizationId">ID of the destination organization</param>
        [Preserve]
        public InlineObject2(System.Guid destinationOrganizationId)
        {
            DestinationOrganizationId = destinationOrganizationId;
        }

        /// <summary>
        /// ID of the destination organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "destinationOrganizationId", IsRequired = true, EmitDefaultValue = true)]
        public System.Guid DestinationOrganizationId{ get; }
    
    }
}

