//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// InlineResponse2001 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "inline_response_200_1")]
    internal class InlineResponse2001
    {
        /// <summary>
        /// Creates an instance of InlineResponse2001.
        /// </summary>
        /// <param name="results">results param</param>
        [Preserve]
        public InlineResponse2001(List<UnityProjectV1> results = default)
        {
            Results = results;
        }

        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<UnityProjectV1> Results{ get; }
    
    }
}

