//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// InlineResponse2005 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "inline_response_200_5")]
    internal class InlineResponse2005
    {
        /// <summary>
        /// Creates an instance of InlineResponse2005.
        /// </summary>
        /// <param name="total">The total number of items matched by the request.</param>
        /// <param name="results">results param</param>
        [Preserve]
        public InlineResponse2005(int total = default, List<UnityUserGuestProjectV1> results = default)
        {
            Total = total;
            Results = results;
        }

        /// <summary>
        /// The total number of items matched by the request.
        /// </summary>
        [Preserve]
        [DataMember(Name = "total", EmitDefaultValue = false)]
        public int Total{ get; }
        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<UnityUserGuestProjectV1> Results{ get; }
    
    }
}

