//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// InlineResponse2003 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "inline_response_200_3")]
    internal class InlineResponse2003
    {
        /// <summary>
        /// Creates an instance of InlineResponse2003.
        /// </summary>
        /// <param name="offset">Offset used by the request.</param>
        /// <param name="limit">Limit used by the request.</param>
        /// <param name="total">The total number of items matched by the request.</param>
        /// <param name="results">results param</param>
        [Preserve]
        public InlineResponse2003(int offset = default, int limit = default, int total = default, List<UnityProjectMemberV1> results = default)
        {
            Offset = offset;
            Limit = limit;
            Total = total;
            Results = results;
        }

        /// <summary>
        /// Offset used by the request.
        /// </summary>
        [Preserve]
        [DataMember(Name = "offset", EmitDefaultValue = false)]
        public int Offset{ get; }
        /// <summary>
        /// Limit used by the request.
        /// </summary>
        [Preserve]
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public int Limit{ get; }
        /// <summary>
        /// The total number of items matched by the request.
        /// </summary>
        [Preserve]
        [DataMember(Name = "total", EmitDefaultValue = false)]
        public int Total{ get; }
        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<UnityProjectMemberV1> Results{ get; }
    
    }
}

