//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// InlineObject6 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "inline_object_6")]
    internal class InlineObject6
    {
        /// <summary>
        /// Creates an instance of InlineObject6.
        /// </summary>
        /// <param name="name">Name of the environment</param>
        [Preserve]
        public InlineObject6(string name)
        {
            Name = name;
        }

        /// <summary>
        /// Name of the environment
        /// </summary>
        [Preserve]
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name{ get; }
    
    }
}

