//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// InlineResponse201 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "inline_response_201")]
    internal class InlineResponse201
    {
        /// <summary>
        /// Creates an instance of InlineResponse201.
        /// </summary>
        /// <param name="filename">Filename being generated</param>
        /// <param name="iconUrl">Public URL of the uploaded icon</param>
        [Preserve]
        public InlineResponse201(string filename = default, string iconUrl = default)
        {
            Filename = filename;
            IconUrl = iconUrl;
        }

        /// <summary>
        /// Filename being generated
        /// </summary>
        [Preserve]
        [DataMember(Name = "filename", EmitDefaultValue = false)]
        public string Filename{ get; }
        /// <summary>
        /// Public URL of the uploaded icon
        /// </summary>
        [Preserve]
        [DataMember(Name = "iconUrl", EmitDefaultValue = false)]
        public string IconUrl{ get; }
    
    }
}

