//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// InlineResponse200 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "inline_response_200")]
    internal class InlineResponse200
    {
        /// <summary>
        /// Creates an instance of InlineResponse200.
        /// </summary>
        /// <param name="total">Number of projects</param>
        /// <param name="offset">Offset used for pagination</param>
        /// <param name="limit">Limit used for pagination</param>
        /// <param name="results">results param</param>
        [Preserve]
        public InlineResponse200(int total = default, int offset = default, int limit = default, List<UnityProjectV1> results = default)
        {
            Total = total;
            Offset = offset;
            Limit = limit;
            Results = results;
        }

        /// <summary>
        /// Number of projects
        /// </summary>
        [Preserve]
        [DataMember(Name = "total", EmitDefaultValue = false)]
        public int Total{ get; }
        /// <summary>
        /// Offset used for pagination
        /// </summary>
        [Preserve]
        [DataMember(Name = "offset", EmitDefaultValue = false)]
        public int Offset{ get; }
        /// <summary>
        /// Limit used for pagination
        /// </summary>
        [Preserve]
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public int Limit{ get; }
        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<UnityProjectV1> Results{ get; }
    
    }
}

