//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// UnityUserContextV1 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "unity.UserContext.v1")]
    internal class UnityUserContextV1
    {
        /// <summary>
        /// Creates an instance of UnityUserContextV1.
        /// </summary>
        /// <param name="user">user param</param>
        /// <param name="organization">organization param</param>
        /// <param name="project">project param</param>
        /// <param name="environment">environment param</param>
        [Preserve]
        public UnityUserContextV1(UnityUserContextV1User user = default, UnityUserContextV1Organization organization = default, UnityUserContextV1Project project = default, UnityUserContextV1Environment environment = default)
        {
            User = user;
            Organization = organization;
            Project = project;
            Environment = environment;
        }

        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "user", EmitDefaultValue = false)]
        public UnityUserContextV1User User{ get; }
        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "organization", EmitDefaultValue = false)]
        public UnityUserContextV1Organization Organization{ get; }
        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "project", EmitDefaultValue = false)]
        public UnityUserContextV1Project Project{ get; }
        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "environment", EmitDefaultValue = false)]
        public UnityUserContextV1Environment Environment{ get; }
    
    }
}

