//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// UnityUserOrganizationsV1Organizations model
    /// </summary>
    [Preserve]
    [DataContract(Name = "unity_UserOrganizations_v1_organizations")]
    internal class UnityUserOrganizationsV1Organizations
    {
        /// <summary>
        /// Creates an instance of UnityUserOrganizationsV1Organizations.
        /// </summary>
        /// <param name="id">ID of the organization</param>
        /// <param name="genesisId">ID provided by Genesis</param>
        /// <param name="name">Name of the organization</param>
        /// <param name="role">Role of the user in the organization</param>
        /// <param name="address">address param</param>
        [Preserve]
        public UnityUserOrganizationsV1Organizations(System.Guid id = default, string genesisId = default, string name = default, string role = default, UnityAddressV1 address = default)
        {
            Id = id;
            GenesisId = genesisId;
            Name = name;
            Role = role;
            Address = address;
        }

        /// <summary>
        /// ID of the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public System.Guid Id{ get; }
        /// <summary>
        /// ID provided by Genesis
        /// </summary>
        [Preserve]
        [DataMember(Name = "genesisId", EmitDefaultValue = false)]
        public string GenesisId{ get; }
        /// <summary>
        /// Name of the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name{ get; }
        /// <summary>
        /// Role of the user in the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "role", EmitDefaultValue = false)]
        public string Role{ get; }
        /// <summary>
        /// 
        /// </summary>
        [Preserve]
        [DataMember(Name = "address", EmitDefaultValue = false)]
        public UnityAddressV1 Address{ get; }
    
    }
}

