//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// UnityEnvironmentV1 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "unity.Environment.v1")]
    internal class UnityEnvironmentV1
    {
        /// <summary>
        /// Creates an instance of UnityEnvironmentV1.
        /// </summary>
        /// <param name="id">ID of the environment</param>
        /// <param name="projectId">ID of the project</param>
        /// <param name="projectGenesisId">ID provided by Genesis, for a small number of projects this ID will not be a UUID for legacy reasons, so treat it as a string ID</param>
        /// <param name="name">Name of the environment</param>
        /// <param name="isDefault">Indicates if the environment is the default environment for the project</param>
        /// <param name="createdAt">UTC date and time describing when the entity was created</param>
        /// <param name="updatedAt">UTC date and time describing when the entity was last updated</param>
        /// <param name="archivedAt">UTC date and time describing when the entity was last archived (null if not archived)</param>
        [Preserve]
        public UnityEnvironmentV1(System.Guid id = default, System.Guid projectId = default, string projectGenesisId = default, string name = default, bool isDefault = default, DateTime createdAt = default, DateTime updatedAt = default, DateTime? archivedAt = default)
        {
            Id = id;
            ProjectId = projectId;
            ProjectGenesisId = projectGenesisId;
            Name = name;
            IsDefault = isDefault;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            ArchivedAt = archivedAt;
        }

        /// <summary>
        /// ID of the environment
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public System.Guid Id{ get; }
        /// <summary>
        /// ID of the project
        /// </summary>
        [Preserve]
        [DataMember(Name = "projectId", EmitDefaultValue = false)]
        public System.Guid ProjectId{ get; }
        /// <summary>
        /// ID provided by Genesis, for a small number of projects this ID will not be a UUID for legacy reasons, so treat it as a string ID
        /// </summary>
        [Preserve]
        [DataMember(Name = "projectGenesisId", EmitDefaultValue = false)]
        public string ProjectGenesisId{ get; }
        /// <summary>
        /// Name of the environment
        /// </summary>
        [Preserve]
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name{ get; }
        /// <summary>
        /// Indicates if the environment is the default environment for the project
        /// </summary>
        [Preserve]
        [DataMember(Name = "isDefault", EmitDefaultValue = true)]
        public bool IsDefault{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was created
        /// </summary>
        [Preserve]
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was last updated
        /// </summary>
        [Preserve]
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public DateTime UpdatedAt{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was last archived (null if not archived)
        /// </summary>
        [Preserve]
        [DataMember(Name = "archivedAt", EmitDefaultValue = false)]
        public DateTime? ArchivedAt{ get; }
    
    }
}

