//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// UnityUserContextV1Project model
    /// </summary>
    [Preserve]
    [DataContract(Name = "unity_UserContext_v1_project")]
    internal class UnityUserContextV1Project
    {
        /// <summary>
        /// Creates an instance of UnityUserContextV1Project.
        /// </summary>
        /// <param name="id">ID of the project</param>
        /// <param name="genesisId">ID provided by Genesis, for a small number of projects this ID will not be a UUID for legacy reasons, so treat it as a string ID</param>
        /// <param name="name">Name of the project</param>
        /// <param name="coppa">COPPA value of the project, one of “unspecified”, “compliant”, or “not_compliant”</param>
        /// <param name="kidsStoreCompliance">Kids Store Compliance value for the project, true if either Apple Kids Category or Google Designed for Families is enabled</param>
        /// <param name="organizationId">ID of the organization where the project belongs to</param>
        /// <param name="organizationGenesisId">Organization ID provided by Genesis where the project belongs to</param>
        /// <param name="iconUrl">URL for the icon of the project (either a custom icon or a mobile store icon)</param>
        /// <param name="roles">User&#39;s roles within the project</param>
        /// <param name="features">Project feature toggles</param>
        /// <param name="createdAt">UTC date and time describing when the entity was created</param>
        /// <param name="updatedAt">UTC date and time describing when the entity was last updated</param>
        /// <param name="archivedAt">UTC date and time describing when the entity was last archived (null if not archived)</param>
        /// <param name="defaultEnvironmentId">Default environment ID of the project</param>
        [Preserve]
        public UnityUserContextV1Project(System.Guid id = default, string genesisId = default, string name = default, string coppa = default, bool kidsStoreCompliance = default, System.Guid organizationId = default, string organizationGenesisId = default, string iconUrl = default, List<string> roles = default, object features = default, DateTime createdAt = default, DateTime updatedAt = default, DateTime? archivedAt = default, System.Guid defaultEnvironmentId = default)
        {
            Id = id;
            GenesisId = genesisId;
            Name = name;
            Coppa = coppa;
            KidsStoreCompliance = kidsStoreCompliance;
            OrganizationId = organizationId;
            OrganizationGenesisId = organizationGenesisId;
            IconUrl = iconUrl;
            Roles = roles;
            Features = new JsonObject(features);
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            ArchivedAt = archivedAt;
            DefaultEnvironmentId = defaultEnvironmentId;
        }

        /// <summary>
        /// ID of the project
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public System.Guid Id{ get; }
        /// <summary>
        /// ID provided by Genesis, for a small number of projects this ID will not be a UUID for legacy reasons, so treat it as a string ID
        /// </summary>
        [Preserve]
        [DataMember(Name = "genesisId", EmitDefaultValue = false)]
        public string GenesisId{ get; }
        /// <summary>
        /// Name of the project
        /// </summary>
        [Preserve]
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name{ get; }
        /// <summary>
        /// COPPA value of the project, one of “unspecified”, “compliant”, or “not_compliant”
        /// </summary>
        [Preserve]
        [DataMember(Name = "coppa", EmitDefaultValue = false)]
        public string Coppa{ get; }
        /// <summary>
        /// Kids Store Compliance value for the project, true if either Apple Kids Category or Google Designed for Families is enabled
        /// </summary>
        [Preserve]
        [DataMember(Name = "kidsStoreCompliance", EmitDefaultValue = true)]
        public bool KidsStoreCompliance{ get; }
        /// <summary>
        /// ID of the organization where the project belongs to
        /// </summary>
        [Preserve]
        [DataMember(Name = "organizationId", EmitDefaultValue = false)]
        public System.Guid OrganizationId{ get; }
        /// <summary>
        /// Organization ID provided by Genesis where the project belongs to
        /// </summary>
        [Preserve]
        [DataMember(Name = "organizationGenesisId", EmitDefaultValue = false)]
        public string OrganizationGenesisId{ get; }
        /// <summary>
        /// URL for the icon of the project (either a custom icon or a mobile store icon)
        /// </summary>
        [Preserve]
        [DataMember(Name = "iconUrl", EmitDefaultValue = false)]
        public string IconUrl{ get; }
        /// <summary>
        /// User&#39;s roles within the project
        /// </summary>
        [Preserve]
        [DataMember(Name = "roles", EmitDefaultValue = false)]
        public List<string> Roles{ get; }
        /// <summary>
        /// Project feature toggles
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(JsonObjectConverter))]
        [DataMember(Name = "features", EmitDefaultValue = false)]
        public JsonObject Features{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was created
        /// </summary>
        [Preserve]
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was last updated
        /// </summary>
        [Preserve]
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public DateTime UpdatedAt{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was last archived (null if not archived)
        /// </summary>
        [Preserve]
        [DataMember(Name = "archivedAt", EmitDefaultValue = false)]
        public DateTime? ArchivedAt{ get; }
        /// <summary>
        /// Default environment ID of the project
        /// </summary>
        [Preserve]
        [DataMember(Name = "defaultEnvironmentId", EmitDefaultValue = false)]
        public System.Guid DefaultEnvironmentId{ get; }
    
    }
}

