//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// UnityOrganizationMemberV1 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "unity.OrganizationMember.v1")]
    internal class UnityOrganizationMemberV1
    {
        /// <summary>
        /// Creates an instance of UnityOrganizationMemberV1.
        /// </summary>
        /// <param name="groupGenesisId">ID provided by Genesis for the group that links the user to the organization</param>
        /// <param name="groupName">Name for the group that links the user to the organization</param>
        /// <param name="role">The role for the user within the organization</param>
        /// <param name="userEmail">The email of the user</param>
        /// <param name="userGenesisId">ID of the user as provided by Genesis</param>
        /// <param name="userId">ID of the user</param>
        /// <param name="userName">Name of the user</param>
        [Preserve]
        public UnityOrganizationMemberV1(string groupGenesisId = default, string groupName = default, string role = default, string userEmail = default, string userGenesisId = default, System.Guid userId = default, string userName = default)
        {
            GroupGenesisId = groupGenesisId;
            GroupName = groupName;
            Role = role;
            UserEmail = userEmail;
            UserGenesisId = userGenesisId;
            UserId = userId;
            UserName = userName;
        }

        /// <summary>
        /// ID provided by Genesis for the group that links the user to the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "groupGenesisId", EmitDefaultValue = false)]
        public string GroupGenesisId{ get; }
        /// <summary>
        /// Name for the group that links the user to the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "groupName", EmitDefaultValue = false)]
        public string GroupName{ get; }
        /// <summary>
        /// The role for the user within the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "role", EmitDefaultValue = false)]
        public string Role{ get; }
        /// <summary>
        /// The email of the user
        /// </summary>
        [Preserve]
        [DataMember(Name = "userEmail", EmitDefaultValue = false)]
        public string UserEmail{ get; }
        /// <summary>
        /// ID of the user as provided by Genesis
        /// </summary>
        [Preserve]
        [DataMember(Name = "userGenesisId", EmitDefaultValue = false)]
        public string UserGenesisId{ get; }
        /// <summary>
        /// ID of the user
        /// </summary>
        [Preserve]
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public System.Guid UserId{ get; }
        /// <summary>
        /// Name of the user
        /// </summary>
        [Preserve]
        [DataMember(Name = "userName", EmitDefaultValue = false)]
        public string UserName{ get; }
    
    }
}

