//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// UnityUserContextV1Organization model
    /// </summary>
    [Preserve]
    [DataContract(Name = "unity_UserContext_v1_organization")]
    internal class UnityUserContextV1Organization
    {
        /// <summary>
        /// Creates an instance of UnityUserContextV1Organization.
        /// </summary>
        /// <param name="id">ID of the organization</param>
        /// <param name="genesisId">ID provided by Genesis</param>
        /// <param name="name">Name of the organization</param>
        /// <param name="industryType">Industry type of the organization</param>
        /// <param name="roles">User&#39;s roles within the organization</param>
        /// <param name="features">Organization feature toggles</param>
        /// <param name="createdAt">UTC date and time describing when the entity was created</param>
        /// <param name="updatedAt">UTC date and time describing when the entity was last updated</param>
        [Preserve]
        public UnityUserContextV1Organization(System.Guid id = default, string genesisId = default, string name = default, string industryType = default, List<string> roles = default, object features = default, DateTime createdAt = default, DateTime updatedAt = default)
        {
            Id = id;
            GenesisId = genesisId;
            Name = name;
            IndustryType = industryType;
            Roles = roles;
            Features = new JsonObject(features);
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
        }

        /// <summary>
        /// ID of the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public System.Guid Id{ get; }
        /// <summary>
        /// ID provided by Genesis
        /// </summary>
        [Preserve]
        [DataMember(Name = "genesisId", EmitDefaultValue = false)]
        public string GenesisId{ get; }
        /// <summary>
        /// Name of the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name{ get; }
        /// <summary>
        /// Industry type of the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "industryType", EmitDefaultValue = false)]
        public string IndustryType{ get; }
        /// <summary>
        /// User&#39;s roles within the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "roles", EmitDefaultValue = false)]
        public List<string> Roles{ get; }
        /// <summary>
        /// Organization feature toggles
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(JsonObjectConverter))]
        [DataMember(Name = "features", EmitDefaultValue = false)]
        public JsonObject Features{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was created
        /// </summary>
        [Preserve]
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was last updated
        /// </summary>
        [Preserve]
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public DateTime UpdatedAt{ get; }
    
    }
}

