//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// UnityUserContextV1User model
    /// </summary>
    [Preserve]
    [DataContract(Name = "unity_UserContext_v1_user")]
    internal class UnityUserContextV1User
    {
        /// <summary>
        /// Creates an instance of UnityUserContextV1User.
        /// </summary>
        /// <param name="id">ID of the user</param>
        /// <param name="genesisId">ID provided by Genesis</param>
        /// <param name="name">Name of the user</param>
        /// <param name="email">Email of the user</param>
        /// <param name="roles">List of user&#39;s global roles. Applicable only to Unity employees.</param>
        /// <param name="features">User feature toggles</param>
        /// <param name="createdAt">UTC date and time describing when the entity was created</param>
        /// <param name="updatedAt">UTC date and time describing when the entity was last updated</param>
        [Preserve]
        public UnityUserContextV1User(System.Guid id = default, string genesisId = default, string name = default, string email = default, List<string> roles = default, object features = default, DateTime createdAt = default, DateTime updatedAt = default)
        {
            Id = id;
            GenesisId = genesisId;
            Name = name;
            Email = email;
            Roles = roles;
            Features = new JsonObject(features);
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
        }

        /// <summary>
        /// ID of the user
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public System.Guid Id{ get; }
        /// <summary>
        /// ID provided by Genesis
        /// </summary>
        [Preserve]
        [DataMember(Name = "genesisId", EmitDefaultValue = false)]
        public string GenesisId{ get; }
        /// <summary>
        /// Name of the user
        /// </summary>
        [Preserve]
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name{ get; }
        /// <summary>
        /// Email of the user
        /// </summary>
        [Preserve]
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email{ get; }
        /// <summary>
        /// List of user&#39;s global roles. Applicable only to Unity employees.
        /// </summary>
        [Preserve]
        [DataMember(Name = "roles", EmitDefaultValue = false)]
        public List<string> Roles{ get; }
        /// <summary>
        /// User feature toggles
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(JsonObjectConverter))]
        [DataMember(Name = "features", EmitDefaultValue = false)]
        public JsonObject Features{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was created
        /// </summary>
        [Preserve]
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was last updated
        /// </summary>
        [Preserve]
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public DateTime UpdatedAt{ get; }
    
    }
}

