//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.DeploymentWindow.Environments.Client.Http;



namespace Unity.Services.DeploymentWindow.Environments.Client.Models
{
    /// <summary>
    /// UnityOrganizationV1 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "unity.Organization.v1")]
    internal class UnityOrganizationV1
    {
        /// <summary>
        /// Creates an instance of UnityOrganizationV1.
        /// </summary>
        /// <param name="id">ID of the organization</param>
        /// <param name="genesisId">ID provided by Genesis</param>
        /// <param name="name">Name of the organization</param>
        /// <param name="industryType">Industry type of the organization</param>
        /// <param name="createdAt">UTC date and time describing when the entity was created</param>
        /// <param name="updatedAt">UTC date and time describing when the entity was last updated</param>
        [Preserve]
        public UnityOrganizationV1(System.Guid id = default, string genesisId = default, string name = default, string industryType = default, DateTime createdAt = default, DateTime updatedAt = default)
        {
            Id = id;
            GenesisId = genesisId;
            Name = name;
            IndustryType = industryType;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
        }

        /// <summary>
        /// ID of the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public System.Guid Id{ get; }
        /// <summary>
        /// ID provided by Genesis
        /// </summary>
        [Preserve]
        [DataMember(Name = "genesisId", EmitDefaultValue = false)]
        public string GenesisId{ get; }
        /// <summary>
        /// Name of the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name{ get; }
        /// <summary>
        /// Industry type of the organization
        /// </summary>
        [Preserve]
        [DataMember(Name = "industryType", EmitDefaultValue = false)]
        public string IndustryType{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was created
        /// </summary>
        [Preserve]
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt{ get; }
        /// <summary>
        /// UTC date and time describing when the entity was last updated
        /// </summary>
        [Preserve]
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public DateTime UpdatedAt{ get; }
    
    }
}

